language: go
sudo: false

go:
    - 1.4.2
    - tip
before_install: 
    - curl http://git.gthomas.eu/gthomas/oracle-instantclient.tar.xz | tar xJf -
      #- /sbin/ldconfig $(pwd)/lib
    - export CGO_CFLAGS=-I./include
    - export CGO_LDFLAGS=-I./lib
before_script:
    - go test -i . ./oracle/
script:
    - go test ./... '-dsn=system/oracle@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=git.gthomas.eu)(PORT=49161)))(CONNECT_DATA=(SERVICE_NAME=xe)))'
