language: go
sudo: required

go:
    - 1.4.2
      #- tip
env:
    - secure: "YkNq7PZEUYh4JRtEjYXXynKwKxlhpHbtOv48sJHtMNjjyZp3WSultA/RkWdy8OcqfkERDPKEDKYNyX4M10BLQbLcpd0l6NKZqklqwtHjEbXh2Ty4mWDOSukBRMot+fZqBHO8BZrOEWFCyUoI6R4kigVBKfq4H+JH3KVASvsSQdU="
before_install: 
    - wget https://github.com/barnybug/s3/releases/download/1.0.0/s3-linux-amd64 && mv s3-linux-amd64 s3 && chmod +x s3
    - ./s3 get s3://tgulacsi-oracle-instantclient/
    - sudo apt-get install libaio1
    - sudo dpkg -i oracle-instantclient12.1-basiclite_12.1.0.2.0-2_amd64.deb
    - sudo dpkg -i oracle-instantclient12.1-devel_12.1.0.2.0-2_amd64.deb
    - echo /usr/lib/oracle/12.1/client64/lib/ | sudo tee /etc/ld.so.conf.d/oracle.conf && sudo ldconfig
    - export CGO_CFLAGS=-I/usr/include/oracle/12.1/client64
    - export CGO_LDFLAGS=-L/usr/lib/oracle/12.1/client64/lib
    - mkdir -p $HOME/gopath/src/gopkg.in
    - ln -s $HOME/gopath/src/github.com/go-goracle/goracle $HOME/gopath/src/gopkg.in/goracle.v1
install: go get -t gopkg.in/goracle.v1
before_script:
    - cd $HOME/gopath/src/gopkg.in/goracle.v1
    - go test -i . ./oracle/
script:
    - go test . ./oracle '-dsn=system/oracle@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=git.gthomas.eu)(PORT=49161)))(CONNECT_DATA=(SERVICE_NAME=xe)))'
