language: go
sudo: false

go:
    - 1.4.2
    - tip
before_install: 
    - curl http://git.gthomas.eu/gthomas/oracle-instantclient.tar.xz | sudo tar xaf - -C /
    - sudo ldconfig /usr/lib/oracle/12.1/client64/lib
    - export CGO_CFLAGS=-I/usr/include/oracle/12.1/client64
    - export CGO_LDFLAGS=-I/usr/lib/oracle/12.1/client64
before_script:
    - go test -i . ./oracle/
script:
    - go test ./... '-dsn=system/oracle@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=git.gthomas.eu)(PORT=49161)))(CONNECT_DATA=(SERVICE_NAME=xe)))'
